<?php

use Illuminate\Database\Seeder;

class CnaeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Cnae::create([ 'codigo' => '8511-2/00', 'descricao' => 'Educação infantil – creche', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8512-1/00', 'descricao' => 'Educação infantil – pré-escola', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8513-9/00 ', 'descricao' => 'Ensino fundamental', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8520-1/00', 'descricao' => 'Ensino médio', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8531-7/00', 'descricao' => 'Educação superior – Graduação', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8532-5/00', 'descricao' => 'Educação superior – graduação e pós-graduação', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8533-3/00', 'descricao' => 'Educação superior – Pós-graduação e extensão', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8541-4/00', 'descricao' => 'Educação profissional de nível técnico', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8542-2/00', 'descricao' => 'Educação profissional de nível tecnológico', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8591-1/00', 'descricao' => 'Ensino de esportes', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8592-9/01', 'descricao' => 'Ensino de dança', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8593-7/00', 'descricao' => 'Ensino de Idiomas', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8599-6/04', 'descricao' => 'Treinamento em desenvolvimento profissional e geracional', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8599-6/05', 'descricao' => 'Cursos preparatórios para concursos', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '8599-6/99', 'descricao' => 'Outras atividades de ensino não especificadas anteriormente', 'areas_id' => '1']);
        \App\Cnae::create([ 'codigo' => '3250-7/06', 'descricao' => 'Serviço de prótese dentária', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '3250-7/09', 'descricao' => 'Serviço de laboratório óptico', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8122-2/00', 'descricao' => 'Imunização e controle de pragas urbanas', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8610-1/01', 'descricao' => 'Atividades de atendimento hospitalar, exceto pronto-socorro e unidades para atendimento a urgências', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8621-6/01', 'descricao' => 'UTI móvel', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8621-6/02', 'descricao' => 'Serviços móveis de atendimento a urgências, exceto por UTI móvel', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8622-4/00', 'descricao' => 'Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8630-5/01', 'descricao' => 'Atividades médica ambulatorial com recursos para realização de procedimentos cirúrgicos', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8630-5/02', 'descricao' => 'Atividades médica ambulatorial com recursos para realização de exames complementares', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8630-5/03', 'descricao' => 'Atividade médica ambulatorial restrita a consultas', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8630-5/04', 'descricao' => 'Atividade odontológica', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8630-5/06', 'descricao' => 'Serviços de vacinação e imunização humana', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8630-5/99', 'descricao' => 'Atividades de atenção ambulatorial não especificadas anteriormente', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/04', 'descricao' => 'Serviço de tomografia', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/05', 'descricao' => 'Serviço de diagnóstico por imagem com uso de radiação ionizante, exceto tomografia', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/06', 'descricao' => 'Serviço de Ressonância Magnética', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/07', 'descricao' => 'Serviço de diagnóstico por imagem sem uso de radiação ionizante, exceto ressonância magnética', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/08', 'descricao' => 'Serviço de diagnóstico por registro gráfico- ECG, EEG e outros exames análogos', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/09', 'descricao' => 'Serviço de diagnóstico por métodos ópticos-endoscopia e outros exames análogos', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8640-2/99', 'descricao' => 'Atividades de serviços de complementação diagnóstica e terapêutica não especificada anteriormente', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/01', 'descricao' => 'Atividades de enfermagem', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/02', 'descricao' => 'Atividades de profissionais da nutrição', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/03', 'descricao' => 'Atividades de psicologia e psicanálise', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/04', 'descricao' => 'Atividades de fisioterapia', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/05', 'descricao' => 'Atividades de terapia ocupacional', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/06', 'descricao' => 'Atividade de fonoaudiologia', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8650-0/07', 'descricao' => 'Atividade de terapia, de nutrição enteral e parenteral', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8690-9/03', 'descricao' => 'Atividade de acupuntura', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8690-9/04', 'descricao' => 'Atividade de podologia', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8690-9/99', 'descricao' => 'Outras atividades de atenção à saúde humana não especificadas anteriormente', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8711-5/01', 'descricao' => 'Clínicas e residências geriátricas', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8711-5/02', 'descricao' => 'Instituições de longa permanência para idosos', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8711-5/03', 'descricao' => 'Atividades de assistência a deficientes físicos, imunodeprimidos e convalescentes', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8711-5/05', 'descricao' => 'Condomínios residenciais para idosos', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8712-3/00', 'descricao' => 'Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente no domicílio', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8720-4/01', 'descricao' => 'Atividade de centros de assistência psicossocial', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '8720-4/99', 'descricao' => 'Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química não especificadas anteriormente', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '9603-3/02', 'descricao' => 'Serviços de cremação', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '9603-3/03', 'descricao' => 'Serviços de sepultamento', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '9603-3/04', 'descricao' => 'Serviços de funerárias', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '9603-3/99', 'descricao' => 'Atividades funerárias e serviços relacionados não especificados anteriormente', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '4664-8/00', 'descricao' => 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto-médico-hospitalar; partes e peças', 'areas_id' => '2']);
        \App\Cnae::create([ 'codigo' => '4644-3/01', 'descricao' => 'Comércio atacadista de medicamentos e droga de uso humano', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '4644-3/02', 'descricao' => 'Comércio atacadista de medicamentos e drogas de uso veterinário', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '4645-1/01', 'descricao' => 'Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, hospitalar e de laboratórios', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '4645-1/02', 'descricao' => 'Comércio atacadista de próteses e artigos de ortopedia', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '4645-1/03', 'descricao' => 'Comércio atacadista de produtos odontológicos', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '4773-3/00', 'descricao' => 'Comércio varejista de artigos médicos e ortopédicos', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '4774-1/00', 'descricao' => 'Comércio varejista de artigos de óptica', 'areas_id' => '3']);
        \App\Cnae::create([ 'codigo' => '3600-6/02', 'descricao' => 'Distribuição de água por caminhões', 'areas_id' => '4']);
        \App\Cnae::create([ 'codigo' => '3600-6/01', 'descricao' => 'Captação, tratamento e distribuição de água', 'areas_id' => '5']);
        \App\Cnae::create([ 'codigo' => '4623-1/01', 'descricao' => 'Comércio atacadista de animais vivos', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4623-1/99', 'descricao' => 'Comércio atacadista de matérias-primas agrícolas não especificadas anteriormente', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4646-0/01', 'descricao' => 'Comércio atacadista de cosméticos e produtos de perfumaria', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4646-0/02', 'descricao' => 'Comércio atacadista de produtos de higiene pessoal', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4647-8/01', 'descricao' => 'Comércio atacadista de artigos de escritório e de papelaria', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4649-4/08', 'descricao' => 'Comércio atacadista de produtos de higiene, limpeza e conservação domiciliar', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4649-4/09', 'descricao' => 'Comércio atacadista de produtos de higiene, limpeza e conservação domiciliar, com atividade de fracionamento e acondicionamento associada', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4692-3/00', 'descricao' => 'Comércio atacadista de mercadorias em geral, com predominância de insumo agropecuários', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4693-1/00', 'descricao' => 'Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4724-5/00', 'descricao' => 'Comércio varejista de hortifrutigranjeiros', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4729-6/02', 'descricao' => 'Comércio varejista de mercadorias em lojas de conveniência', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4761-0/03', 'descricao' => 'Comércio varejista de artigos de papelaria', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4771-7/04', 'descricao' => 'Comércio varejista de medicamentos veterinários', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4772-5/00', 'descricao' => 'Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4789-0/04', 'descricao' => 'Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4789-0/05', 'descricao' => 'Comércio varejista de produtos saneantes domissanitários', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '5510-8/01', 'descricao' => 'Hotéis', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '5510-8/02', 'descricao' => 'Apart-hotéis', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '5510-8/03', 'descricao' => 'Motéis', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '5590-6/01', 'descricao' => 'Albergues, exceto assistenciais', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '5590-6/03', 'descricao' => 'Pensões (alojamento)', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '5590-6/99', 'descricao' => 'Outros alojamentos não especificados anteriormente', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '8129-0/00', 'descricao' => 'Atividades de limpeza não especificadas anteriormente', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '8230-0/01', 'descricao' => 'Serviço de organização de feiras, congressos,exposições e festas', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '8230-0/02', 'descricao' => 'Casas das festas e eventos', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '8730-1/01', 'descricao' => 'Orfanatos', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '8730-1/02', 'descricao' => 'Albergues assistenciais', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9312-3/00', 'descricao' => 'Clubes sociais, esportivos e similares', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9313-1/00', 'descricao' => 'Atividades de condicionamento físico', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9319-1/99', 'descricao' => 'Outras atividades esportivas não especificadas anteriormente', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9329-8/01', 'descricao' => 'Discotecas, danceterias, salões de danças e similares', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9329-8/99', 'descricao' => 'Outras atividades de recreação e lazer não especificadas anteriormente', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9430-8/00', 'descricao' => 'Atividades de associações de defesa de direitos sociais', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9602-5/01', 'descricao' => 'Cabeleireiros, manicures e pedicure', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9602-5/02', 'descricao' => 'Atividades de estética e outros serviços de cuidados com a beleza', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9609-2/05', 'descricao' => 'Atividades de sauna e banhos', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9609-2/06', 'descricao' => 'Serviços de tatuagem e colocação de piercing', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9609-2/07', 'descricao' => 'Alojamento de animais domésticos', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '9609-2/08', 'descricao' => 'Higiene e embelezamento de animais domésticos', 'areas_id' => '7']);
        \App\Cnae::create([ 'codigo' => '4712-1/00', 'descricao' => 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios – minimercados, mercearias e armazéns', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4721-1/02', 'descricao' => 'Padaria e confeitaria com predominância de revenda', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5612-1/00', 'descricao' => 'Serviços ambulantes de alimentação', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5620-1/01', 'descricao' => 'Fornecimento de alimentos preparados preponderantemente para empresas', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5620-1/02', 'descricao' => 'Serviços de alimentação para eventos e recepções - bufê', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5620-1/03', 'descricao' => 'Cantinas – serviços de alimentação privativos', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5620-1/04', 'descricao' => 'Fornecimento de alimentos preparados preponderantemente para consumo domiciliar', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '7500-1/00', 'descricao' => 'Atividades Veterinárias', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '8121-4/00', 'descricao' => 'Limpeza de prédios e em domicílios', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4623-1/09', 'descricao' => 'Comércio atacadista de alimentos para animais', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4631-1/00', 'descricao' => 'Comércio atacadista de leite e laticínios', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4632-0/01', 'descricao' => 'Comércio atacadista de cereais e leguminosas beneficiados', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4632-0/02', 'descricao' => 'Comércio atacadista de farinhas, amidos e féculas', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4632-0/03', 'descricao' => 'Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas, com atividades de fracionamento e acondicionamento associada', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4633-8/01', 'descricao' => 'Comércio atacadista de frutas, verduras, raízes, tubérculos, hortaliças e legumes frescos', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4633-8/02', 'descricao' => 'Comércio atacadista de aves vivas e ovos', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4633-8/03', 'descricao' => 'Comércio atacadista de coelhos e outros pequenos animais vivos para alimentação', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4634-6/01', 'descricao' => 'Comércio atacadista de carnes bovinas e suínas e derivados', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4634-6/02', 'descricao' => 'Comércio atacadista de aves abatidas e derivados', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4634-6/03', 'descricao' => 'Comércio atacadista de pescados e frutos do mar', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4634-6/99', 'descricao' => 'Comércio atacadista de carne e derivados de outros animais', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4635-4/01', 'descricao' => 'Comércio atacadista de água mineral', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4635-4/03', 'descricao' => 'Comércio atacadista de bebidas com atividade de fracionamento e acondicionamento associada', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4635-4/99', 'descricao' => 'Comércio atacadista de bebidas não especificadas anteriormente', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/01', 'descricao' => 'Comércio atacadista de café torrado, moído e solúvel', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/02', 'descricao' => 'Comércio atacadista de açúcar', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/03', 'descricao' => 'Comércio atacadista de óleos e gorduras', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/04', 'descricao' => 'Comércio atacadista de pães, bolos, biscoitos e Similares', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/05', 'descricao' => 'Comércio atacadista de massas alimentícias', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/06', 'descricao' => 'Comércio atacadista de sorvetes', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/07', 'descricao' => 'Comércio atacadista de chocolates, confeitos, balas, bombons e semelhantes', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4637-1/99', 'descricao' => 'Comércio atacadista especializado em outros produtos alimentícios não especificados anteriormente', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4639-7/01', 'descricao' => 'Comércio atacadista de produtos alimentícios em geral', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4691-5/00', 'descricao' => 'Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4711-3/01', 'descricao' => 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4711-3/02', 'descricao' => 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios – supermercados', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4721-1/03', 'descricao' => 'Comércio varejista de laticínios e frios', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4721-1/04', 'descricao' => 'Comércio varejista de doces, balas, bombons e semelhantes', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4722-9/01', 'descricao' => 'Comércio varejista de carnes - açougues', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4722-9/02', 'descricao' => 'Peixaria', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4723-7/00', 'descricao' => 'Comércio varejista de bebidas', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '4729-6/99', 'descricao' => 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5611-2/01', 'descricao' => 'Restaurantes e similares', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5611-2/02', 'descricao' => 'Bares e outros estabelecimentos especializados em servir bebidas', 'areas_id' => '8']);
        \App\Cnae::create([ 'codigo' => '5611-2/03', 'descricao' => 'Lanchonetes, casas de chá, de sucos e similares', 'areas_id' => '8']);
    }
}
